DROP SEQUENCE playerIdSeq;
DROP SEQUENCE gameIdSeq;
DROP SEQUENCE pointsIdSeq;

CREATE SEQUENCE playerIdSeq	MINVALUE 0 START WITH 0 INCREMENT BY 1;
CREATE SEQUENCE gameIdSeq	MINVALUE 1 START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE pointsIdSeq	MINVALUE 1 START WITH 1 INCREMENT BY 1;
